version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "cookiecutter"
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 99
 