project:
  type: website
  execute-dir: project
  output-dir: ../docs


website:
  sidebar:
    style: "docked"
    search: true
    contents: auto
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



