name: OneDrive to GitHub with rclone

on:
  issues:
    types: [opened]

# Add permissions block
permissions:
  contents: write
  issues: write

jobs:
  sync_files:
    runs-on: ubuntu-latest
    if: github.event.issue.state == 'open'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          sudo curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone (using rclone config file)
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
          rclone version

      - name: Create data directory
        run: mkdir -p data

      - name: Copy files from OneDrive
        run: |
          rclone -v copy OneDrive: ./data --include "/*-ecas-export.db"

      - name: Commit changes
        id: commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/* # Add all files in the data directory
          if git diff --staged --quiet; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
            echo "No changes to commit"
          else
            git commit -m "Update DB files from OneDrive triggered by issue #${{ github.event.issue.number }}"
            git push origin HEAD:${{ github.ref }}
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger the workflow
        if: success() && steps.commit.outputs.changes_made == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-workflow

      - name: Delete files from OneDrive
        if: success()
        run: |
          rclone -v delete OneDrive: --include "/*-ecas-export.db"

      - name: Close issue
        if: success()
        run: |
          gh issue close ${{ github.event.issue.number }} --comment "✅ Successfully synced files from OneDrive to GitHub and cleaned up source files."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          